---
app:
  build: .
  volumes:
    - ./resizer:/home/ec2-user/resizer
    - ./lambda.py:/home/ec2-user/lambda.py
    - ./bin:/home/ec2-user/bin
    - ./dist:/tmp/dist
    - ./deploy:/home/ec2-user/deploy
  environment:
    - DEPLOY_ENV
    - AWS_ACCESS_KEY_ID=AKIAJWMDCQHUDSYCXDOA
    - AWS_SECRET_ACCESS_KEY=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
    - AWS_DEFAULT_REGION=ap-southeast-2
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    # - AWS_SESSION_TOKEN
    # - BUILDKITE_BUILD_NUMBER
