---
app:
  build: .
  volumes:
    - ./resizer:/home/ec2-user/resizer
    - ./lambda.py:/home/ec2-user/lambda.py
    - ./bin:/home/ec2-user/bin
    - ./dist:/tmp/dist
    - ./deploy:/home/ec2-user/deploy
  environment:
    - DEPLOY_ENV
    - SOURCE_IMAGES_BUCKET
    - AWS_DEFAULT_REGION
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - BUILDKITE_BUILD_NUMBER

ci:
  extends:
    file: docker-compose.yml
    service: app
  volumes:
    - ./tests:/home/ec2-user/tests
